# Generated by Django 4.2 on 2026-02-16 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='playlist_url',
            field=models.URLField(blank=True, default='', max_length=500, null=True),
        ),
    ]
